# .github/workflows/idx-sync.yml
name: "IDX → Supabase Incremental Sync"

on:
  schedule:
    # runs every 2 hours at minute 0
    - cron: '0 */2 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30    # incremental runs finish quickly
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run incremental sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          IDX_API_URL: ${{ secrets.IDX_API_URL }}
          IDX_API_KEY: ${{ secrets.IDX_API_KEY }}
        run: npm run sync